on:
  push

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build and test
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: npm test

  build-and-test-with-workaround:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: buld and test with workaround
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: npm test || true
      - run: npm run build
      - run: npm test